const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 14,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Hush Puppies Men',
    image: '/images/02.jpg',
    description:
      'They apply their philosophy of fun, comfortable, genuine style to every shoe they make - from work to weekend',
    brand: 'Amazon',
    category: 'shoes',
    price: 125.99,
    countInStock: 15,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: '8',
    name: 'Gildan Adult Ultra Cotton T-shirt',
    image: '/images/04.jpg',
    description:
      'Whether wearing it for work or play, the Gildan Ultra Cotton Adult T-Shirt is a wardrobe basic that works for just about any occasion',
    brand: '',
    category: 't shirt',
    price: 40.99,
    countInStock: 16,
    rating: 4,
    numReviews: 11,
  },
  {
    _id: '9',
    name: 'Deer Stags Mens Williamsburg Oxford',
    image: '/images/08.jpg',
    description:
      'Introducing your new everyday go-to shoe! Dress it up for formal occasions or wear it to work',
    brand: 'Williamsburg ',
    category: 'shoes',
    price: 50.99,
    countInStock: 17,
    rating: 4,
    numReviews: 13,
  },
  {
    _id: '10',
    name: 'Kipling Womens Sabian Mini Crossbody',
    image: '/images/07.jpg',
    description:
      'A mini bag with major possibilities. Keep the Sabian Mini Handbag around, its a brilliant way to tote around your essentials',
    brand: 'sabian',
    category: 'bag',
    price: 29.99,
    countInStock: 18,
    rating: 4,
    numReviews: 16,
  },
]

export default products
